name: Exercise23-CICD


on:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/cicd-pipeline/values.yaml"


permissions:
  contents: write


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install Dependencies
        run: |
          pip install -r requirements.txt


      - name: Run Tests
        run: |
          pytest -v



  build-and-push:

    needs: test

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v4



      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1



      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2



      - name: Build Docker Image
        run: |
          docker build \
          -t cicd-pipeline-git:${{ github.sha }} .



      - name: Tag Image
        run: |
          docker tag cicd-pipeline-git:${{ github.sha }} \
          823729324830.dkr.ecr.us-east-1.amazonaws.com/cicd-pipeline-git:${{ github.sha }}



      - name: Push Image
        run: |
          docker push \
          823729324830.dkr.ecr.us-east-1.amazonaws.com/cicd-pipeline-git:${{ github.sha }}



      - name: Update Helm Image Tag
        run: |
          sed -i \
          "s/tag:.*/tag: \"${{ github.sha }}\"/" \
          helm/cicd-pipeline/values.yaml



      - name: Commit Helm Update
        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"


          git add helm/cicd-pipeline/values.yaml


          git commit \
          -m "Update image tag to ${{ github.sha }}" \
          || echo "No changes to commit"


          git push
